### ISSUE TITLE
Fix hero blue box spacing issues

### ISSUE THREAD

**Issue by MichelleGlauser** [MichelleGlauser/techtonica#78] opened 2017-03-27 04:14 UTC
On Desktop Chrome, the blue box with white text over the hero image has extra space at the top once the  window is shrunk from its full size:

![screen shot 2017-03-26 at 8 58 10 pm](https://cloud.githubusercontent.com/assets/1952773/24340698/175231d8-1269-11e7-9df2-deffb3915ee4.png)
![screen shot 2017-03-26 at 8 58 18 pm](https://cloud.githubusercontent.com/assets/1952773/24340696/175196ec-1269-11e7-874b-f7fc565c31a7.png)
![screen shot 2017-03-26 at 8 58 28 pm](https://cloud.githubusercontent.com/assets/1952773/24340697/1751af6a-1269-11e7-96d8-6533e7436ea4.png)

This same issue does not seem to appear in Desktop or Mobile Safari.

**Comment by cachar** [comment] 2017-03-28 06:33
I can't reproduce the error in desktop Chrome

#### Desktop Chrome:
<img width="398" alt="techtonica__bridging_the_tech_gap" src="https://cloud.githubusercontent.com/assets/16581819/24391607/b7007a5e-1355-11e7-820d-e0dd9429e028.png">

#### Desktop Safari:
<img width="499" alt="techtonica__bridging_the_tech_gap" src="https://cloud.githubusercontent.com/assets/16581819/24391632/d268f262-1355-11e7-96b5-b54e68d25614.png">

#### Desktop Firefox:
<img width="334" alt="techtonica__bridging_the_tech_gap" src="https://cloud.githubusercontent.com/assets/16581819/24391660/fb2fa97a-1355-11e7-98f9-816fb6e8c651.png">

**Comment by MichelleGlauser** [comment] 2017-03-28 11:20
I'm still getting it, but I just realized it only does it when I'm hooked up to a large screen. Have you tried that? Is this an edge case, or do you think a lot of people visiting our site connect to a larger screen (at work, for example)?

**Comment by emilong** [comment] 2017-03-28 19:13
I was able to reproduce this - looks like the issue is with the `height: 100vh;` in the `main-header` class when the width is really small. I think this is probably an edge case though, because it only starts to look weird when the user has a very narrow but tall screen/window

If you wanted to fix it though, I think it might make it easier not to have the hero as the background image of the header, at least for that media query. In that case, the `height: 100vh` is the only thing making the header large enough for it to show. I can give it a try if you like.

HTH! :)

**Comment by MichelleGlauser** [comment] 2017-03-29 05:20
Thanks, @emilong! If you wanted to try changing the hero as background image thing, that would be great!

**Comment by emilong** [comment] 2017-03-29 17:29
Gave it a shot with https://github.com/MichelleGlauser/techtonica/pull/86, switching between a background image and full `<img>` tag depending on media query. I'm sure there are other ways, but that was what I was able to come up with. LMK if you have other ideas! :smile:

**Comment by KGmajor** [comment] 2019-07-25 05:00
Resolved in PR #86

**Closed by KGmajor** 2019-07-25 05:00 UTC
