### ISSUE TITLE
Relocate binary assets

### ISSUE THREAD

**Issue by abacon** [MichelleGlauser/techtonica#3] opened 2016-07-20 06:26 UTC
My home internet is abysmally slow, and git says the repo is at 70mb and counting at 30%. The repo seems a bit large, likely because of some large binary assets that were committed and then removed. We should do some `git filter-branch` magic to remove the relevant files from commits so that the repo size can go down. This obviously isn't very pressing, I just wanted to document it somewhere.

**Comment by abacon** [comment] 2016-07-20 06:30
After looking at the sheer number of photos that we're keeping in the repo, we should definitely think of moving these to s3 or some other external hosting place. Git is not well-suited to tracking binary files. What do y'all think?

**Comment by KGmajor** [comment] 2019-07-25 05:38
Duplicate of another ticket for pruning images.

**Closed by KGmajor** 2019-07-25 05:38 UTC
Labels: duplicate
